## Numpy

In [121]:
import numpy as np


### N-dimensional arrays

#### General

Ndarrays objects are multidimensional, homogeneous containers of fixed-size items.

In [122]:
list = [[19.23, 39.14, 67.78, 98.49], [56.78, 88.78, 99.01, 99.99], [12.00, 76.87, 91.09, 10.01], [99.01, 70.32, 64.89, 36.68]]

array = np.array(list) # Construct Ndarray

array

array([[ 19.23,  39.14,  67.78,  98.49],
       [ 56.78,  88.78,  99.01,  99.99],
       [ 12.  ,  76.87,  91.09,  10.01],
       [ 99.01,  70.32,  64.89,  36.68]])

In [123]:
array.shape # Ndarray Structure

(4, 4)

In [124]:
array[0] # Ndarray Indexing

array([ 19.23,  39.14,  67.78,  98.49])

In [125]:
array.ndim # Number Of Dimensions

2

In [126]:
array.item(1,1) # Select Item

88.78

#### Transformation

In [127]:
listed = array.tolist() # Transform An Array Into A List

listed

[[19.23, 39.14, 67.78, 98.49],
 [56.78, 88.78, 99.01, 99.99],
 [12.0, 76.87, 91.09, 10.01],
 [99.01, 70.32, 64.89, 36.68]]

In [128]:
reshaped = array.reshape(2,8) # Reshape An Array Structure
reshaped

array([[ 19.23,  39.14,  67.78,  98.49,  56.78,  88.78,  99.01,  99.99],
       [ 12.  ,  76.87,  91.09,  10.01,  99.01,  70.32,  64.89,  36.68]])

In [129]:
swaped = reshaped.swapaxes(0,1) # Swap Array Axes
swaped

array([[ 19.23,  12.  ],
       [ 39.14,  76.87],
       [ 67.78,  91.09],
       [ 98.49,  10.01],
       [ 56.78,  99.01],
       [ 88.78,  70.32],
       [ 99.01,  64.89],
       [ 99.99,  36.68]])

In [130]:
flattened = reshaped.flatten() # Reduce The Array To One Dimension
flattened

array([ 19.23,  39.14,  67.78,  98.49,  56.78,  88.78,  99.01,  99.99,
        12.  ,  76.87,  91.09,  10.01,  99.01,  70.32,  64.89,  36.68])

#### Manipulation

In [131]:
repeated = array.repeat(3) # Repeats Elements Of An Array
repeated

array([ 19.23,  19.23,  19.23,  39.14,  39.14,  39.14,  67.78,  67.78,
        67.78,  98.49,  98.49,  98.49,  56.78,  56.78,  56.78,  88.78,
        88.78,  88.78,  99.01,  99.01,  99.01,  99.99,  99.99,  99.99,
        12.  ,  12.  ,  12.  ,  76.87,  76.87,  76.87,  91.09,  91.09,
        91.09,  10.01,  10.01,  10.01,  99.01,  99.01,  99.01,  70.32,
        70.32,  70.32,  64.89,  64.89,  64.89,  36.68,  36.68,  36.68])

In [132]:
sortedarray = np.sort(array) # Sort An Array Within Items

print sortedarray

[[ 19.23  39.14  67.78  98.49]
 [ 56.78  88.78  99.01  99.99]
 [ 10.01  12.    76.87  91.09]
 [ 36.68  64.89  70.32  99.01]]


In [133]:
completelysortedarray = np.sort(array, axis=None) # Sort The Whole Array

completelysortedarray

array([ 10.01,  12.  ,  19.23,  36.68,  39.14,  56.78,  64.89,  67.78,
        70.32,  76.87,  88.78,  91.09,  98.49,  99.01,  99.01,  99.99])

#### Calculation

In [170]:
array.argmax() # Returns Index Of The Maximum Value

array.min() # Returns Minimum Value

# np.maximum(array1, array2) # Maximum Between 2 Arrays

array.ptp() # Peak To Peak: Maximum - Minimum

array.ptp(0) # Column Maximum - Column Minimum

array.ptp(1) # Row Maximum - Row Minimum

array([ 79.26,  43.21,  81.08,  62.33])

In [171]:
array.clip(45,76) # Returns An Array With Values Within The Arguments Range

array([[ 45.  ,  45.  ,  67.78,  76.  ],
       [ 56.78,  76.  ,  76.  ,  76.  ],
       [ 45.  ,  76.  ,  76.  ,  45.  ],
       [ 76.  ,  70.32,  64.89,  45.  ]])

In [172]:
array.round(decimals=0) #Rounds The Floating Array Values

array([[  19.,   39.,   68.,   98.],
       [  57.,   89.,   99.,  100.],
       [  12.,   77.,   91.,   10.],
       [  99.,   70.,   65.,   37.]])

In [173]:
array.sum() # Sums The Whole Array

array.cumsum() # Gives The Cumulative Array Sum

array([   19.23,    58.37,   126.15,   224.64,   281.42,   370.2 ,
         469.21,   569.2 ,   581.2 ,   658.07,   749.16,   759.17,
         858.18,   928.5 ,   993.39,  1030.07])

In [158]:
array.mean(0) # Array Average Value

array.var() # Array Variance

array.std() # Standard Deviation

31.167207620500346

In [159]:
array

array([[ 19.23,  39.14,  67.78,  98.49],
       [ 56.78,  88.78,  99.01,  99.99],
       [ 12.  ,  76.87,  91.09,  10.01],
       [ 99.01,  70.32,  64.89,  36.68]])

In [160]:
array.prod() # Product Of Array Values

array.cumprod() # Cumulated Product

array([  1.92300000e+01,   7.52662200e+02,   5.10154439e+04,
         5.02451107e+06,   2.85291739e+08,   2.53282006e+10,
         2.50774514e+12,   2.50749436e+14,   3.00899323e+15,
         2.31301310e+17,   2.10692363e+19,   2.10903056e+20,
         2.08815115e+22,   1.46838789e+24,   9.52836903e+25,
         3.49500576e+27])

In [161]:
array[0].mean() # Mean Of The First Row

array[:,0].mean() # Mean Of The First Column

46.755000000000003

In [162]:
array

array([[ 19.23,  39.14,  67.78,  98.49],
       [ 56.78,  88.78,  99.01,  99.99],
       [ 12.  ,  76.87,  91.09,  10.01],
       [ 99.01,  70.32,  64.89,  36.68]])

#### Indexing/Slicing

In [163]:
flattened = [ 19.23,  39.14,  67.78,  98.49,  56.78,  88.78,  99.01,  99.99,
        12.  ,  76.87,  91.09,  10.01,  99.01,  70.32,  64.89,  36.68]


flattened[1:7:2] # Selects Index 1 To 7, 2 By 2

[39.14, 98.49, 88.78]

In [164]:
def differentthantwo(element):
    return element == 2 or element == 3

filter(lessthanzero, flattened) # Conditional Selection For A List

array[(array != 2) & (array < 20)] # Conditional Selection For An Array

array([ 19.23,  12.  ,  10.01])

#### Miscellaneous

In [165]:
data = np.random.randn(2,3) # Create An Array With Random Numbers Between -1 And 1

data # Random.Rand => Betwen 0 And 1

array([[-1.72379332, -0.76851404,  1.42639033],
       [ 0.89531347,  0.08657664,  1.46681758]])

In [166]:
data * 10 # Multiply Each Value

array([[-17.23793317,  -7.68514041,  14.26390332],
       [  8.95313466,   0.86576636,  14.66817577]])

In [167]:
np.zeros(15) # Create 15 Zeros

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])

In [168]:
np.arange(15) # Create a Range Of Numbers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [169]:
np.sqrt(np.arange(15)) # Square Root

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])